// Допустим, мы используем конструкцию try catch внутри функции. И нам для чего-то понадобилось использовать return или throw в одном из блоков. В любом случае код внутри блока finally будет выполнен. А код снаружи блока будет проигнорирован, мы просто выйдем из функции
